# GitLab CI-konfiguraatiorunko kursiille Ohjelmoinnin tekniikat 2017-2018
# Uudelleennimä tämä tiedosto gitlab-ci

# Imagena on käytössä Alpine Linux, 
# johon asennettu Qt 5.9.1 ja tarvittavat käännöstyökalut

# Jos käytät harjoitustyön toteuttamiseen muuta tekniikka kuin Qt ja C++,
# ota yhteyttä kurssihenkilökuntaan saadaksesi käyttöösi sopivan imagen.

image: alpine-qt:latest
# cachetetaan build-vaiheessa luodut (testi)binäärit, jotta ne siirtyvät eri vaiheiden välillä.
cache:
    paths:
      - /TrainGame/Test/debug/testgame.o
stages: 
  - build
  - test

build:
  only: 
    - none
  stage: build
  
  script:
    - cd TrainGame/Test
    - qmake Test.pro
    - make
    
testGame:
  only: 
    - none
  stage: test
  script:
    - ./testgame

# Tarkempi kuvaus GitLab CI:n konfigurointiin https://docs.gitlab.com/ce/ci/yaml/